CREATE
-- ALTER
FUNCTION CREATE_IDCUSTOMERTOUR()
RETURNS CHAR(10)
AS
BEGIN
	DECLARE @ID CHAR(10)
	IF(NOT EXISTS (SELECT *
				   FROM CUSTOMER_TOUR))
	BEGIN
		SET @ID = 'CST0000001'
		RETURN @ID
	END
	ELSE
	BEGIN
		SELECT @ID = CAST(CAST(MIN(RIGHT(ID_CUSTOMER_TOUR,7)) AS INT) + 1 AS CHAR(10))
		FROM CUSTOMER_TOUR
		WHERE (RIGHT(ID_CUSTOMER_TOUR,7) + 1) NOT IN (SELECT RIGHT(ID_CUSTOMER_TOUR,7) FROM CUSTOMER_TOUR)
	END

	DECLARE @TEMP INT = CAST(@ID AS INT)
	DECLARE @COUNT INT = 0

	WHILE(@TEMP >0)
	BEGIN
		SET @TEMP = @TEMP/10
		SET @COUNT = @COUNT + 1
	end
    
	DECLARE @CNT int =0
	WHILE(@CNT <> (7-@COUNT))
	BEGIN
		SET @ID = '0' + @ID
		SET @CNT = @CNT + 1
	END
	SET @ID = 'CST' + @ID
	RETURN @ID
END

