CREATE
-- ALTER
FUNCTION CREATE_IDDISCOUNT()
RETURNS CHAR(10)
AS
BEGIN
	DECLARE @ID CHAR(10)
	IF(NOT EXISTS (SELECT *
				   FROM DISCOUNT_PROMOTION))
	BEGIN
		SET @ID = 'DIS0000001'
		RETURN @ID
	END
	ELSE
	BEGIN
		SELECT @ID = CAST(CAST(MIN(RIGHT(ID_DISCOUNT,7)) AS INT) + 1 AS CHAR(10))
		FROM DISCOUNT_PROMOTION
		WHERE (RIGHT(ID_DISCOUNT,7) + 1) NOT IN (SELECT RIGHT(ID_DISCOUNT,7) FROM DISCOUNT_PROMOTION)
	END

	DECLARE @TEMP INT = CAST(@ID AS INT)
	DECLARE @COUNT INT = 0

	WHILE(@TEMP >0)
	BEGIN
		SET @TEMP = @TEMP/10
		SET @COUNT = @COUNT + 1
	end
    
	DECLARE @CNT int =0
	WHILE(@CNT <> (7-@COUNT))
	BEGIN
		SET @ID = '0' + @ID
		SET @CNT = @CNT + 1
	END
	SET @ID = 'DIS' + @ID
	RETURN @ID
END
GO
CREATE
--ALTER
PROC USP_AddDISCOUNT(
	@NAME NVARCHAR(80),
	@STARTDATE DATETIME,
	@ENDDATE DATETIME,
	@DESCRIPT NVARCHAR(200),
	@TYPEDISCOUNT NVARCHAR(20),
	@REQUIREMENT INT,
	@DISCOUNT_RATE FLOAT
)
AS
BEGIN TRANSACTION
	BEGIN TRY
		IF(EXISTS (SELECT NAME FROM DISCOUNT_PROMOTION WHERE NAME = @NAME))
		BEGIN
			ROLLBACK TRAN
			RETURN 0
		END
		IF(DATEDIFF(D,@STARTDATE,@ENDDATE) <=0)
		BEGIN
			ROLLBACK TRAN
			RETURN 0
		END
	END TRY
	BEGIN CATCH
		print(N'Thông tin không hợp lệ')
		ROLLBACK TRAN
	END CATCH
	DECLARE @IDDISCOUNT CHAR(10) = DBO.CREATE_IDDISCOUNT()
	IF(@REQUIREMENT = -1)
	BEGIN
		INSERT INTO DISCOUNT_PROMOTION VALUES(@IDDISCOUNT,@NAME,@STARTDATE,@ENDDATE,@DESCRIPT,@TYPEDISCOUNT,NULL,@DISCOUNT_RATE);
	END
	ELSE IF(@DISCOUNT_RATE = -1)
	BEGIN
		INSERT INTO DISCOUNT_PROMOTION VALUES(@IDDISCOUNT,@NAME,@STARTDATE,@ENDDATE,@DESCRIPT,@TYPEDISCOUNT,@REQUIREMENT,NULL);
	END
COMMIT
EXEC USP_AddDISCOUNT 'MEO MOE MOE MEO', '2023-05-17 04:11:31.000', '2023-06-14 00:10:09.000',NULL,N'Giảm giá',1,-1
