CREATE
-- ALTER
FUNCTION CREATE_IDSERVICE_BF()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(10)
	IF(NOT EXISTS (SELECT *
				   FROM SERVICE_FORM))
	BEGIN
		SET @ID = 'SF001'
		RETURN @ID
	END
	ELSE
	BEGIN
		SELECT @ID = CAST(CAST(MIN(RIGHT(ID_SERVICE_FORM,3)) AS INT) + 1 AS CHAR(5))
		FROM SERVICE_FORM
		WHERE (RIGHT(ID_SERVICE_FORM,3) + 1) NOT IN (SELECT RIGHT(ID_SERVICE_FORM,3) FROM SERVICE_FORM)
	END

	DECLARE @TEMP INT = CAST(@ID AS INT)
	DECLARE @COUNT INT = 0

	WHILE(@TEMP >0)
	BEGIN
		SET @TEMP = @TEMP/10
		SET @COUNT = @COUNT + 1
	end
    
	DECLARE @CNT int =0
	WHILE(@CNT <> (3-@COUNT))
	BEGIN
		SET @ID = '0' + @ID
		SET @CNT = @CNT + 1
	END
	SET @ID = 'SF' + @ID
	RETURN @ID
END
GO
CREATE
--ALTER
PROC USP_AddSERVICE_BF(
	@IDCUS CHAR(5),
	@NAMESERVICE NVARCHAR(100),
	@SERVICEID CHAR(10),
	@DESCRIPT NVARCHAR(100),
	@PRICE INT,
	@AMOUNT INT,
	@EMPID CHAR(5),
	@TOTAL_PRICE INT,
	@USINGDATE DATETIME,
	@DISCOUNT FLOAT
	--@ID_BILL CHAR(5)
)
AS
BEGIN TRANSACTION
	DECLARE @IDSERVICE CHAR(10) = DBO.CREATE_IDSERVICE_BF()
	INSERT INTO SERVICE_FORM VALUES(@IDSERVICE,@NAMESERVICE,@DESCRIPT,@PRICE,@AMOUNT,@SERVICEID,@EMPID,@IDCUS)
	INSERT INTO SERVICE_BILL VALUES(@IDSERVICE,@USINGDATE,@TOTAL_PRICE,@DISCOUNT,@TOTAL_PRICE*(100-@DISCOUNT)/100,'Đã thanh toán',@IDSERVICE,'B0043')
COMMIT

select * from SERVICE_BILL
select * from SERVICE_FORM

EXEC USP_AddSERVICE_BF NULL,N'gÂU GÂU',NULL,'LA LA',1241223,23,NULL,51253234,NULL,4