CREATE
-- ALTER
FUNCTION CREATE_IDSERVICE()
RETURNS CHAR(10)
AS
BEGIN
	DECLARE @ID CHAR(10)
	IF(NOT EXISTS (SELECT *
				   FROM HOTEL_SERVICE))
	BEGIN
		SET @ID = 'SEV0000001'
		RETURN @ID
	END
	ELSE
	BEGIN
		SELECT @ID = CAST(CAST(MIN(RIGHT(ID_SERVICE,7)) AS INT) + 1 AS CHAR(10))
		FROM HOTEL_SERVICE
		WHERE (RIGHT(ID_SERVICE,7) + 1) NOT IN (SELECT RIGHT(ID_SERVICE,7) FROM HOTEL_SERVICE)
	END

	DECLARE @TEMP INT = CAST(@ID AS INT)
	DECLARE @COUNT INT = 0

	WHILE(@TEMP >0)
	BEGIN
		SET @TEMP = @TEMP/10
		SET @COUNT = @COUNT + 1
	end
    
	DECLARE @CNT int =0
	WHILE(@CNT <> (7-@COUNT))
	BEGIN
		SET @ID = '0' + @ID
		SET @CNT = @CNT + 1
	END
	SET @ID = 'SEV' + @ID
	RETURN @ID
END
GO
CREATE
--ALTER
PROC USP_AddSERVICE(
	@NAME NVARCHAR(80),
	@DESCRIPT NVARCHAR(200),
	@PRICE INT,
	@UNIT NCHAR(10)
)
AS
BEGIN TRANSACTION
	BEGIN TRY
		IF(EXISTS (SELECT NAME FROM HOTEL_SERVICE WHERE NAME = @NAME))
		BEGIN
			ROLLBACK TRAN
			RETURN 0
		END
	END TRY

	BEGIN CATCH
		print(N'Thông tin không hợp lệ')
		ROLLBACK TRAN
	END CATCH
	DECLARE @IDSERVICE CHAR(10) = DBO.CREATE_IDSERVICE()
	INSERT INTO HOTEL_SERVICE VALUES(@IDSERVICE,@NAME,@DESCRIPT,@PRICE,@UNIT,N'Khả dụng')
COMMIT
