CREATE
-- ALTER
FUNCTION CREATE_IDRULESHOTEL()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(5)

	IF(NOT EXISTS (SELECT *
				   FROM RULES
				   WHERE ID_RULE LIKE 'R%' AND ID_RULE NOT LIKE 'RK%'))
		BEGIN
			SET @ID = 'R0001'
			RETURN @ID
		END
	ELSE
		BEGIN
			SELECT @ID = CAST(CAST(MIN(RIGHT(ID_RULE,4)) AS INT) + 1 AS CHAR(5))
			FROM RULES
			WHERE (RIGHT(ID_RULE,4) + 1) NOT IN (SELECT RIGHT(ID_RULE,4) FROM RULES WHERE ID_RULE LIKE 'R%' AND ID_RULE NOT LIKE 'RK%')
			AND ID_RULE LIKE 'R%' AND ID_RULE NOT LIKE 'RK%'
		END

	DECLARE @TEMP INT = CAST(@ID AS INT)
	DECLARE @COUNT INT = 0

	WHILE(@TEMP >0)
	BEGIN
		SET @TEMP = @TEMP/10
		SET @COUNT = @COUNT + 1
	end
    
	DECLARE @CNT int =0
	WHILE(@CNT <> (4-@COUNT))
	BEGIN
		SET @ID = '0' + @ID
		SET @CNT = @CNT + 1
	END

	SET @ID = 'R' + @ID
	RETURN @ID
END

GO

CREATE
-- ALTER
FUNCTION CREATE_IDRULESOTHERS()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(5)

	IF(NOT EXISTS (SELECT *
				   FROM RULES
				   WHERE ID_RULE LIKE 'RK%'))
		BEGIN
			SET @ID = 'RK001'
			RETURN @ID
		END
	ELSE
		BEGIN
			SELECT @ID = CAST(CAST(MIN(RIGHT(ID_RULE,3)) AS INT) + 1 AS CHAR(5))
			FROM RULES
			WHERE (RIGHT(ID_RULE,3) + 1) NOT IN (SELECT RIGHT(ID_RULE,3) FROM RULES WHERE ID_RULE LIKE 'RK%')
			AND ID_RULE LIKE 'RK%'
		END

	DECLARE @TEMP INT = CAST(@ID AS INT)
	DECLARE @COUNT INT = 0

	WHILE(@TEMP >0)
	BEGIN
		SET @TEMP = @TEMP/10
		SET @COUNT = @COUNT + 1
	end
    
	DECLARE @CNT int =0
	WHILE(@CNT <> (3-@COUNT))
	BEGIN
		SET @ID = '0' + @ID
		SET @CNT = @CNT + 1
	END

	SET @ID = 'RK' + @ID
	RETURN @ID
END

GO

CREATE
-- ALTER
FUNCTION CREATE_IDRULES(
	@TYPE NVARCHAR(80)
)
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID CHAR(5)
	IF(@TYPE LIKE N'%khách sạn')
		BEGIN
			SET @ID = DBO.CREATE_IDRULESHOTEL();
		END
	ELSE IF (@TYPE LIKE N'%chìa khóa')
		BEGIN
			SET @ID = DBO.CREATE_IDRULESOTHERS();
		END
	RETURN @ID;
END
GO
CREATE
--ALTER
PROC USP_AddRULES(
	@NAME NVARCHAR(80),
	@DESCRIPT NVARCHAR(200),
	@TYPE NVARCHAR(80)
)
AS
BEGIN TRANSACTION
	BEGIN TRY
		IF(EXISTS (SELECT NAME FROM RULES WHERE NAME = @NAME))
		BEGIN
			ROLLBACK TRAN
			RETURN 0
		END
	END TRY

	BEGIN CATCH
		print(N'Thông tin không hợp lệ')
		ROLLBACK TRAN
	END CATCH

	DECLARE @IDRULES CHAR(5) = DBO.CREATE_IDRULES(@TYPE)
	INSERT INTO RULES VALUES(@IDRULES,@NAME,@DESCRIPT,GETDATE(),NULL)
COMMIT
SELECT* FROM RULES
EXEC USP_AddRULES N'MÈOs MEO MÉO', 'NdOTHING', N'Quy định chìa khóa'